# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wh4nxuw6axUvMGi9TvVC3ZUy-xhejYY3
"""

#Q1

a = eval(input("Enter a : "));
b = eval(input("Enter b : "));

print(f"Sum : {a+b}");

#Q2

a = float(input("Enter fload number : "));

print(a);
print(type(a));

#Q3

age = eval(input("Enter you age : "));

print(f"{100-age} years left to reach 100 years.");

#Q4

fname = input("Enter your First name : ");
lname = input("Enter your Last name : ");

print(f"Name : {fname} {lname}");

#Q5

radius = float(input("Enter the radius : "));

print("Areas : ", (3.14*radius*radius));

#Q6

num = eval(input("Enter the number : "));

print(num*2);

#Q7

exp = eval(input("Enter expression : "));

print(exp);

#Q8

num1 = int(input("Enter integer number : "));

print(num1+10);

#Q9

num = float(input("Enter float number : "));

print(num);

print(int(num));

#Q10

name = input("Enter your name : ");

print(f"Hello {name}");

#Q11

a = eval(input("Enter a : "));
b = eval(input("Enter b : "));

print(f"Sum : {a+b}");

#Q12

x = eval(input("Enter x : "));
y = eval(input("Enter y : "));

prd = x*y;

print(prd-y);

#Q13

x = True;

if x:
  print(type(x));

#Q14

a = 17;
b = 4;

print(a/b);
print(a%b);

#Q15

num = 6;

prd = num*10;

print(prd-5);

#Q16

prd = 2*3*4;

print(prd-4);

#Q17

a,b,c = 5,6,9;

num = (a*100) + (b*10) + (c*1);

print(num);

#Q18

num = 99;

num += 1;

print(num);

#Q19

num = 4;

num = (num*num) - 1;

print(num);

#Q20

a = 10;
b = 25;

print(a-b);

#Q21

a = 1.234;
b = 2.456;

print(a+b);

#Q22

rad = 2.5;
pie = 3.14;

area = pie * rad * rad;

print(area);

#Q23

l_int = 1000;

num = 2.5;

print(num*l_int);

#Q24

num1, num2 = 2.5,4;

sum = num1 + num2;

print(sum);
print(type(sum));

#Q25

a,b,c = 2.5, 3.5, 7.0;

avg = (a+b+c)/3;

print(f"Average : {avg}");

#Q26

a , b = 4, 8.0;

print(type(a));
print(type(b));

#Q27

a,b = 4,2.0;

prd = a*b;

print(prd);

#Q28

num = 5;

print("Type before Dividing : ", type(num));

ans = 5/2;

print("Type After Dividing : ", type(ans));

#Q29

x = 20;

print(bool(x));

#Q30

x = 0;

print(bool(x));

