# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbAgNYSPZ2wd6-JYSMur78DvygQ-cdrd
"""

#Q1

name = input("Enter the name : ");
print(name);
print(f"Reversed Name : {name[::-1]}");

#Q2

name = input("Enter a name to check : ");

reversed_name = name[::-1];

if name == reversed_name:
  print("This is palidrome");
else:

  print("This is not palindrome");

#Q3

query = "How are you doing today ?";
replaced_query = query.replace(" ", "_");

print(replaced_query);

#Q4

fruit_name = "banana";

print(f"Alphabet a appears {fruit_name.count("a")} times .");

#Q5

fruit_name = "banana";

print(f"Index of first occurance of  'a' is: {fruit_name.index("a")} ");

#Q6

model = "openai";

print(model.upper());

#Q7

query = "HELLO WORLD";

print(query.upper());

#Q8

f_name = "Hello";

l_name = "World";

full_name = f_name + " " + l_name;

print(full_name);

#Q9

word = "programming";

word = word.replace("m", '');

print(word);

#Q10

word = "programming";

extract = word[3:7];

print(extract);

#Q11

word = "Hello World";

print(f"Length of the word is : {len(word)}");

#Q12

word = "hello_everyone";

word = word.replace("everyone", "there");

print(word);

#Q13

line = "hello world how are you";

new_line = line.replace(" ", "-");

print(new_line);

#Q14

text = " messy text ";

text = text.strip();

print(text);

#Q15

text = "Hi there ";

check = text.startswith("Hi");

print(check);

#Q16

text = "I am running";

check = text.endswith("ing");

print(check);

#Q17

text = "welcome to the jungle";

text = text.capitalize();

print(text);

#Q18

ll = ["I", "love", "coding."];

text = " ".join(ll);

print(text);

#Q19

text = "Python is fun";

text = text.lower();

print(text);

text = text.replace(" ", "_");

print(text);

#Q20

text = "Hello World Python";

text = text.split();

text = text[::-1];

print(text);

text = " ".join(text);

print(text);

#Q21

text = "good morning world";

text = text.title();

print(text);

#Q22

line = "apple banana apple mango apple";

count = line.count("apple");

print(count);

#Q23

word = "racecar";

first_letter = word[0];
last_letter = word[-1];

if first_letter == last_letter:
  print("same");
else:
  print("Not same");

#Q24

word = "aXbYcZd";

print(word[1::2]);

#Q25

wordd = "Tomorrow";

f_letter = wordd[0];
l_letter = wordd[-1];

new_word = wordd[-1] + wordd[1:-1] + wordd[0];

print(new_word);

#Q26

line = "Tomorrow is holiday";

line = line.replace('', "#");

print(line);

#Q27

word = "he@llo!#wo$rld";

word = word.replace("@", '');
word = word.replace("!#", '');
word = word.replace("$", '');

print(word);

#Q28

word = "mississippi";

print(word.find("i"));
print(word.index("i"));

#Q29

word = "hello world hello";

word = word.replace("hello", '').strip();

print(word);

#Q29

word = "Hello WorLd";

word = word.swapcase();

print(word);

