# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19As8eHimHkDUfDqUxDfrmBfAB5TDDB0f
"""

#Q1

numbers = [10,20,30,40,50];

print(numbers[1]);
print(numbers[3]);

#Q2

numbers = [1,2,3,4,10,9,8,4]

print(numbers[-1:-4:-1]);

#Q3

numbers = [10,20,30,40,50];

print(max(numbers));
print(min(numbers));

#Q4

letters = ['a', 'q', 'd', 'h','i' ];

letters.sort();

letters[::-1]

#Q5

ll = ['a', 'a', 'd', 'f'];

count = ll.count('a');

print(count)

#Q6

colours = ['yellow', 'green', 'blue', 'red'];

temp = "";

temp = colours[0];

colours[0] = colours[-1];
colours[-1] = temp;
colours

#Q7

l = [25,30,[26,27,28,'hello'],[32,38]];

print(l[2][-1]);

#Q8


l[2][1] = 43;

l

#Q9

l.insert(-1, True)

l

#10

l1 = [4,2,5,10];

l2 = [11,19,18,17];

l3 = sorted(l1+l2);

l3

#Q11

ll = [];

opt1 = input("Enter fruit");

ll.append(opt1);

opt2 = input("Enter fruit");

ll.append(opt2);

opt3 = input("Enter fruit");

ll.append(opt3);

ll

#Q12

ll.extend(["pineapple", "guava", "lichi"]);

ll

#Q13

ll.sort();

ll

#Q14

even = [2,4,6,8];
odd = [1,3,5,7];

odd.extend(even);

odd

#Q15

ll = [4,5,1,2,9,7,10,8];

print("sum", sum(ll));
print("Avg", (sum(ll)/(len(ll))))

#Q16

fruits=['apple','banana','orange','mango']

fruits.pop();

fruits

#Q17

fruits=['apple','banana','orange','mango'];

print(len(fruits));

#Q18

fruits=['apple','banana','orange','mango'];

copied_ll = fruits.copy();

print(copied_ll);

#Q19

city = [];

city.append("Delhi");
city.append("Mumbai");
city.append("Lukhnow");

city

#Q20

city = [];

city.append("Delhi");
city.append("Mumbai");
city.append("Lukhnow");

city2 = ["Punjab", "Rajasthan", "Assam"];

city.extend(city2);

city

#Q21

nums = [1,2,2,1,3,1,1,8,1];

count = nums.count(1);

print(count)

#Q22

ll = [4,5,1,2,9,7,10,8];

ll.sort()

ll[1]

#Q23
nums = [1,2,2,1,3,1,1,8,1];


nums = set(nums)

nums = list(nums);

print(nums);

#Q24

ll = [4,5,1,2,9,7,10,8];

ll.reverse();

ll

#Q25

nums = [1,2,2,1,3,1,1,8,1];

count = nums.count(1);

print(count);

#Q26

ll = [4,5,1,2,9,7,10,8];

ll = ll[::-1];

ll

#Q27

fruits=['apple','banana','orange','mango'];

fruits[-1] = "Pineapple";

print(fruits);

#Q28

fruit1 = ["apple", "banana"];

fruit2 = ["orange", "peach"];

fruits = fruit1 + fruit2;

print(fruits);

#Q29

ll = [1,2,3,4];

new_ll = ll[:];

print(ll);
print(new_ll);

#Q30

ll = [[1,2],[3,4],[5,6]];

print(ll[1][1]);

