# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEmFCwvfBmOrErMp_Ey1fTSlEL52wO3M
"""

#Q1
print(10);

#Q2
print(5,10,15);

#Q3
name = "Dhananjay Puri";
print(name);

#Q4
fname = "Dhananjay";
lname = "Puri";

print(fname, lname);

#Q5
name = "Dhananjay Puri";
city = "New Delhi";

print("My name is {} and I live in {}".format(name,city));

#Q6
age = 36;

print(f"My age is {age}");

#Q7
a = 1;
b = 2;
c = 3;

print(f"a = {a}",f"b = {b}",f"c = {c}", sep='|');

#Q8

print("Python and Rocks!");

#Q9

num1 = 5;
num2 = 8;

print(f"Sum of num1 + num2 = {num1+num2}");

#Q10

name = input("Enter your name - ");
print(f"Hello {name}");

#Q11

city = "New Delhi";

print(city);

#Q12

num1 = 10;
num2 = 20;

temp = num1;
num1 = num2;
num2 = temp;

print(f"Swapped Value num1 = {num1} and num2 = {num2}");

#Q13

i , j , k = 5,10,"Python";

print("i = ", i);
print("j = ", j);
print("k = ", k);

#Q14

color1 = color2 = color3 = "Red";

print(color1);
print(color2);
print(color3);

#Q15

num = 3.14;

print(f"Type of num : {num} is {type(num)}");

#Q16

name = "Dhananjay Puri";
age = 36;

print(f"My name is {name} and I am {age} years old.");

#Q17

a = 5;
b = 3;

print(a*b);

#Q18

is_python_fun = True;

print(is_python_fun);

#Q19

x = 10;

x += 5;

print(x);

#Q20

a=b=c=5;

print(id(a));
print(id(b));
print(id(c));

b = 10;

print(id(a));
print(id(b));
print(id(c));

#Q21

a=b=c=d=e=0;

print(a,b,c,d,e);

print(id(a));
print(id(b));
print(id(c));
print(id(d));
print(id(e));

b = 10;

print(id(b));

#Q22

x = 5;

print(x);

del x;

# print(x);

#Q23
x = 5;
y = 7;

print(f"sum is {x+y}");

#Q24

num1 = 10;
num2 = 20;

num1 , num2 = num2, num1;

print(f"num1 = {num1}");
print(f"num2 = {num2}");

#Q25

result = 5*8;

print(result);

#Q26

a, b = 10, 20;

print(a);
print(b);

#Q27

message = "Good Morning !";

print(message);

del message;

print(message);

#Q28

fname , lname = "Dhananjay", "Puri";

print(fname, lname);

#Q29

num = 10;

num = num + 5;

print(num);

#Q30

greeting = "Hello";

print(greeting);

