# -*- coding: utf-8 -*-
"""tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBml9ks2PPyLVX4ybq35Q9HAO0pS5r8g
"""

#Q1
t = (10,20,30,40,50)

print(t[2]);

#Q2

t = (5,10,15,20,25,30);

print(t[3:]);

#Q3

a = (1,2,3);
b = (4,5,6);

t = tuple(list(a) + list(b));

print(t);

#Q4

t = (7,8);

t = tuple(list(t) + list(t) + list(t));

print(t);

#Q5

t = (5,10,15,20,25,30);

ind = t.index(15);

if ind:
  print(f"15 is present on {ind} index");

#Q6

t = (1,2,3,4,5,6);

print(len(t));

#Q7

t = (10,20,30,40,50);

ind = t.index(50);

print(f"50 is present on {ind} index");

#Q8

t = (2,4,2,6,2,8);

count = t.count(2);

print(count);

#Q9

t = (1,2,3,4,5);

t = list(t);

temp = t[0];

t[0] = t[-1];
t[-1] = temp;

t = tuple(t);

print(t);

#Q10

t = (10,20,30,40);

t = list(t);

t.reverse();

t = tuple(t);

print(t);

# OR

t = (10,20,30,40);

t = t[::-1];

print(t);

#Q11

t = (15,6,89,34);

print(max(t));

#Q12

t = (12,3,77,44);

print(min(t));

#Q13

t = (1,);
print(t)

#Q14

t = (100,200,300);

a , b, c = t;

print(a);
print(b);
print(c);

#Q15

t = (10,20,30,40,50,60);

print(t[1::2]);

#Q16

t = (4, 6, 2, 9, 1)

print(max(t));
print(min(t));

#Q17

t = (9,8,7);

new_t = list(t);

new_t.pop(0);

new_t.insert(0, 99);

new_t = tuple(new_t);

print(t);
print(new_t);

#Q18

a = 1,2;
b = 4,5;
x = 9;

a = list(a);
a.append(x);

a.extend(list(b));

a = tuple(a);

print(a);

#Q19

t = (5,10,15,20);

ind = t.index(15);

print(f"15 is present at {ind} index .");

#Q20

t = (1,3,5,7);

count = t.count(2);

print(count);

#Q21

t = (1,3,5,7,9,11,13);

ind = t.index(11);

print(ind);

#Q22

t = ((1,2), (3,4));

print(t[1][1]);

#Q23

t = (10,20,30,60);

t = list(t);

t.append(99);

t = tuple(t);

print(t);

#Q24

t = (["dog", "cat"]);

print(t[1][0]);

#Q25

t = (10,20,30,40,50);

print(t[1:4]);

#Q26

t = ((5,6),(7,8,9));

print(t[1][-1]);

#Q27

t = (3,5,8,2,7,1,6,4);

t = list(t);
t.sort();

t = tuple(t);

print(t);

#Q28

t = (10,20,60,30,90);

t = list(t);

t.reverse();

t = tuple(t);

print(t);

#Q29

t = (1,2,3,4,5,6,7);

print(t[0:3]);

#Q30

t = (10,20,30,60,40,70);

print(t[2]);

