# -*- coding: utf-8 -*-
"""while loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHxQ7U4OxdpBlTnBdklaWV4KwNeiryWW
"""

#Q1

n = 1;
s = 0;
while n<=50:
  print(n);
  s = s+n;
  n = n+1;

print("sum", s);

#Q2

n = 6;
i = 1;

product = 1;

while i<=n:
  product = product*i;
  i+=1;

print("factorial", product);

#Q3

i = 1;

while i<=10:
  print(i);
  i += 1;

#Q4

i = 1;
l = [];
while True:
  if i % 2 == 0:
    print(i);
    l.append(i);
  if len(l) == 20:
    break;

  i = i +1;

#Q5

num = 54321
i = 0;
s = str(num);
sum = 0;

while i<len(s):
  sum = sum + eval(s[i]);
  i = i +1;

print("sum", sum);

#Q6

num = 54321

s = str(num);
print(len(s))
n = "";
i = 0;
l = len(s)
while l > i:
  print(s[l-1]);
  n = n + s[l-1];
  l = l-1;

n = eval(n);
print(n)

#Q7

while True:

  num = eval(input("Enter the number"));

  if num<0:
    break;

  print(num*num);

#Q8

i = 1;
l = [];
while i<=300:
  if i % 10 == 0:
    print(i);
    l.append(i);

  i += 1;
print(l);

#Q9

i = 0;
num =105;
s = 0;
while num > i:

  print(num);
  num = num -7;

#Q10

num = 10;

while num > 0:
  print(num);
  num = num - 1;

#Q11

num = eval(input("Enter the number : "));
i = 1;
while i <=10:
  print(f"{num} * {i} = ", num*i);
  i += 1;

#Q12

while True:
  num = input("Enter the number");

  if num.isdigit():
    print("Hello");
  else:
    break;

#Q13

i = 1;

while i<=10:
  print(i);
  i += 1;

i = 9;

while i>=1:
  print(i);
  i -= 1;

#Q14
l = [];
while True:
  names = input("Enter name or Enter exit : ");
  if names.lower() == "exit":
    break;
  l.append(names);

print(len(l));
print(l);

#Q15

s = 0;

while True:
  num = input("Enter the number or exit ");
  if num,lower() == "exit":
    break
  s = s + int(num);
print("sum", s);

#Q16

movies = [];

while True:
  value = input("Enter movie or done to exit : ");

  if value.lower() == "done":
    break;

  movies.append(value);

print(movies);

#Q17
l = [];
while True:
  num = input("Enter number or done for exit : ");

  if num.lower() == "done":
    break;

  l.append(int(num));
  if len(l) == 10:
    break;

l.sort();

print("Smallest number", l[0]);
print("Largest number", l[-1]);

#Q18

name = "Python";

i = 0;

while i<len(name):
  print(name[i]);
  i += 1;

#Q19

l = [23,45,25,32,46,33,71,90];

i = 0;

while i<len(l):

  if l[i] % 2 == 1:
    print(l[i]);
  i += 1;

#Q20

n = 50;

i = 1;

while i<n:
  print(i,"--------",n-i)
  i += 1;

#Q21
strr = "madam"

i = 0

palindrome = True;

while i < len(strr)//2:

  if strr[i] == strr[-(i+1)]:
    print(f"{strr[i]} - Matching");


  else:
    palindrome = False;

  i += 1;

if palindrome:
  print("String is palindrome");
else :
  print("String is not palindrome");

#Q22

num = int(input("Enter the number"));

factor = [];

i = 1;

while i<=num:
  if num % i == 0:
    factor.append(i);

  i += 1;

print(factor);

#Q24

i = 1

while i <= 10:

    j = 1

    while j <= i:
        print("*", end=" ")
        j += 1

    print()

    i += 1

#Q25

value = input("Enter the value : ");

vowels = ['a', 'e', 'i', 'o', 'u'];
l = [];
i = 0;

while i<len(value):
  if value[i].lower() in vowels:
    l.append(value[i].lower());
  i += 1;

if len(value)>0:

  print(set(l));
else:
  "No vowels found"

#Q26

l = [];
avg = 0;
sum = 0;
while True:
  num = eval(input("Enter the number : "));
  if num>0:
    l.append(num);
  else:
    if len(l) == 1:
      avg = l[0];
    elif len(l)>1:
      i = 0;

      while i<len(l):
        sum = sum + l[i];

        i += 1;
      avg = sum/len(l);
    break;

print(avg);

#Q27

num = int(input("Enter the number"));

i = 0;

while num >= 0:


  print(num);
  num -= 1;

#Q28

num = input("Enter the number : ");
l = [];
sum = 0;
i = 0;
if len(num)>0:
  while i < len(num):
    l.append(num[i]);
    i += 1;

print(len(l));

#Q29

val = input("Enter the value : ");

num = int(input("Enter how many times is required"));

i = 0;

while i < num:
  print(val);
  i += 1;

#Q23

num1 = int(input("Enter the number1 : "));
num2 = int(input("Enter the number2 : "));

greater = 0;

if num1>num2:
  greater = num1;
else:
  greater = num2;

while True:
  if (greater % num1 == 0) and (greater % num2 == 0):
    print(f"LCM of {num1} and {num2} is {greater}");
    break;
  greater = greater + 1;

