# -*- coding: utf-8 -*-
"""numpy_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYcvnAKWTl-qWYx2nvu3DPMGB32VAMgy
"""

## Extraction in arrays
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80,90]);

print(arr);

#Q6

print(arr[0]);

#Q7

print(arr[-1]);

#Q8

print(arr[4]);

#Q9

print(len(arr));
print(arr[2:7]);

#Q10

print(arr[::2])

#Q11

print(arr[::-1])

#Q12

print(arr[0:5]);

#Q13

print(arr[-3:]);

#Q14

print(arr[::2]);

#Q15

print(arr[1::2]);

#Q16

arr[3] = 400;

print(arr);

#Q17

arr += 5;

print(arr);

#Q18

arr *= 2;

print(arr);

#Q19

print(arr[arr>50]);

#20

print(arr);
print(arr.ndim);
print(arr.shape);
print(arr.dtype);
print(arr.size);

#Q21

arr2 = np.arange(1,20);

print(arr2);

#Q22

arr3 = np.zeros(shape=10);

print(arr3);

#Q23

arr3 = np.zeros(shape=15);

arr3 += 1;

print(arr3);

#Q24

arr4 = np.random.randint(1,100,8);

print(arr4);

#Q25

arr = np.arange(12);
arr = arr.reshape(2,6)

print(arr);

#Q26

arr = np.array([10,20,30,40,50,60,70,80,90]);
len(arr[arr%2==0])

#Q27

print(arr.max())
print(arr.min())

#Q28

print(arr.sum())
print(arr.mean())

#Q29

print(arr[(arr%2==0) & (arr%3==0)])

## Extraction
arr = np.array([12,45,67,23,89,34,90,11,56,78]);

print(arr[[1,3,6]]);

print(arr[[0,4,-1]]);

print(arr[(arr>50) & (arr<80)]);

print(arr[[1,4,7,9]]);

print(arr[(arr%2==0)&(~(arr%5==0))]);

## Append

arr = np.array([10,20,30,40,50]);

print(arr);

arr = np.append(arr,60);

print(arr);

to_add = [70,80,90];

arr = np.append(arr,to_add);

print(arr);

arr2 = np.array([100,110,120]);

arr = np.append(arr, arr2);

print(arr);

arr = np.append(arr, 999);

print(arr);

## Append
x = np.array([11,12,13,14,15,16])

print(x);

arr=np.array([]);

arr = np.append(arr, x[x%2==0]);

print(arr);

arr=np.array([]);

arr = np.append(arr, np.arange(1,6));

print(arr);

## Delete
arr = np.array([10,20,30,40,50,60,70,80,90]);

arr = np.delete(arr,3)

print(arr);

arr = np.delete(arr, [0,-1]);

print(arr);

arr = np.array([10,20,30,40,50,60,70,80,90]);

arr = np.delete(arr,[1,4,6]);

print(arr);

arr = np.array([10,20,30,40,50,60,70,80,90]);

print(arr[arr<=50]);

print(arr[arr%2!=0]);
arr = np.array([10,20,20,30,40,40,50])
arr = np.unique(arr);

print(arr);

## Replace

arr = np.array([10,20,30,40,50,60,70,80,90])

arr[3] = 400;

print(arr);

arr[0] = 999;
arr[-1] = 111;

print(arr);

arr[arr>50] = 0;

print(arr);

arr[arr%2==0] = -1;

print(arr);

arr = np.array([10,20,30,40,50,60,70,80,90])

arr[arr%3==0] = 300;

print(300);

arr = np.array([10,20,30,40,50,60,70,80,90])

arr[[1,4,7]] = 100;

print(arr);

arr[((arr>30) & (arr<70))] = 999;

print(arr);

arr = np.array([10,-5,20,-7,30,-1])

arr[arr<0] = 0;

print(arr);

arr = np.array([10,20,30,40,50,60,70,80,90])

print(arr.max());
print(arr.min());

